export const POLICY_CONSTANTS = {
  UPDATE: 'UPDATE POLICY',
  HR_POLICY: 'HR POLICY',
  COMPANY_POLICY: 'COMPANY POLICY',
  LEAVE_POLICY: 'LEAVE POLICY',
  SICK_LEAVES: 'Sick Leaves',
  ANNUAL_LEAVES: 'Annual Leaves',
};
